### PR TITLE
Introduce media file tab for controlling playback

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC can you take a look and see if there's still many obvious bugs?

**Comment by CoBC** [comment]
The volume slider seams to have no effect, when I change his value, it just returns to 1000
Also some QLabel (E.G. format) has no accessible label asociated

**Comment by bear101** [comment]
@CoBC were you using SpeexDSP when volume had no effect? I've changed volume slider to be disabled if AGC is not enabled in SpeexDSP.

I've also changed the media playback off slider to range from 0-10000 so one can set it more precisely. The best solution would be to change its range depending on the length of the media file.

**Comment by CoBC** [comment]
I use TeamTalk Audio preprocessor. Volume slider still seams to have no effect :(, and the "elapsed" slider don't refresh his value, so, when I click on "Play" button, "Elapsed" slider just became active but with a value of 0

**Comment by bear101** [comment]
If you use the Stream Media file dialog isn't it the same issue with the "Elapsed" slider?

**Comment by CoBC** [comment]
Yes, same issue

**Comment by bear101** [comment]
@CoBC do the labels have to changed in the same as a "user information dialog" in order to be readable for screen readers?

**Comment by CoBC** [comment]
Yes :)

**Review by CoBC — APPROVED** [review]

**Pull request merged**
