### PR TITLE
Option to play sounds for outgoing messages: Fixed #720

### LINKED ISSUE #720: Optional sound when sent a channel or an user message
Hi!

In TeamTalk 5.7 beta classic version there are new sounds that are very good, and as a new feature, TTS says when a private or channel message sent.

Can you add options to enable sound on channel and user message sent? Channel message sent sound was very good in earlier clients to detect lags in TCP connection, and easier to hear the message sent instead of TTS says it.

### PR DESCRIPTION
**Pull request by Oreonan**
I just hope GUI is not broken.

### CODE REVIEW

**Comment by bear101** [comment]
I changed the Qt client so sent message is a separate sound event. I think this is simpler to implement since you can use existing functionality.

**Comment by Oreonan** [comment]
So I must have to do the same on classic?

**Comment by bear101** [comment]
I would suggest the same way

**Comment by bear101** [comment]
> So I must have to do the same on classic?

Yes, please :)

**Comment by Oreonan** [comment]
This have only one inconvenient, sound for private and channel messages 
send is the same. The checkbox respected diference bitween two events :)

Maybe we need to add a different event for each message sent?

**Comment by ChrisDuffley** [comment]
Don't we already have a checkbox for each event separately, unless this is only for TTS in Classic? We'll want both private and channel messages separate I believe.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by Oreonan** [comment]
We have currently a sound event for channel message, and for private 
message, and a TTS event for each type of message also.

**Comment by ChrisDuffley** [comment]
Correct. I'd keep it that way, having 2 different sound events that can be toggled in Prefs would probably be most preferred.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Pull request merged**
