### PR TITLE
Option to use TalkBack for TTS events

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by amirmahdifard** [comment]
@CoBC wy this one is stil not addee? is there any problem with that?

**Comment by CoBC** [comment]
I still haven't any success to finish this feature. Maybe @bear101 or @beqabeqa473 can look to this PR also to try helping me complete the implementation.

**Comment by beqabeqa473** [comment]
Do you have problems with this pr?

**Comment by CoBC** [comment]
Yes, for now I don't know how to complete this, TalkBack requires some 
things to be able to talk but I'm not able to implement it correctly. 
Can you help?

**Comment by beqabeqa473** [comment]
Will try to look into that.

On 5/14/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Yes, for now I don't know how to complete this, TalkBack requires some
> things to be able to talk but I'm not able to implement it correctly.
> Can you help?
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1420#issuecomment-1546825044
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
@CoBC see #1887

**Pull request closed without merging**
