### PR TITLE
Android 11 and beyond requires MANAGE_EXTERNAL_STORAGE to access files

### LINKED ISSUE #973: .tt files don't import under android 11 onsamsung galaxy s20
Ever sense updating to the latest teamtalk for android.  I have triedto import a .tt file only to discover when  I went to the server list.  None of the servers I imported were showing up in the server list.  This wasn't a problem in previous versions of teamtalk on Android.

### PR DESCRIPTION
**Pull request by CoBC**
Should be fixed #973

### CODE REVIEW

**Comment by beqabeqa473** [comment]
not sure this simple fix would work

On 6/10/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Should be fixed #973
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/BearWare/TeamTalk5/pull/1923
>
> -- Commit Summary --
>
>   * Android 11 and beyond requires MANAGE_EXTERNAL_STORAGE to access files
>
> -- File Changes --
>
>     M ChangeLog.txt (1)
>     M Client/TeamTalkAndroid/src/main/AndroidManifest.xml (1)
>
> -- Patch Links --
>
> https://github.com/BearWare/TeamTalk5/pull/1923.patch
> https://github.com/BearWare/TeamTalk5/pull/1923.diff
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1923
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***&gt;
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
@CoBC did you test that this actually fixes the problem?

**Comment by CoBC** [comment]
Unfortunately no, I can't test for now. I just read this method on the internet, but sure it's better if we can test before merging.

**Comment by beqabeqa473** [comment]
lots of things are beeing written in internet, but if we would create
prs by only depending what folks write in internet, that wouldn't be
cool. Not a good practice to just open prs without first testing it
and proofing that this feature works, creating hope for other users
which could ever be true

On 6/11/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Unfortunately no, I can't test for now. I just read this method on the
> internet, but sure it's better if we can test before merging.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1923#issuecomment-1586280880
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
That permission declares all files access, as noted by me in some issues.
First of all, this pr is incomplete, because when granting this permission, user should go to special settings in android settings and grant access to all files by hand, to accomplish this specific intent should be called.
Secondly, this functionality may violate google play policy, Bjoern should fill a declaration form that must be approved by google to further publish an app to google play.

**Comment by CoBC** [comment]
OK, it seams that it's more complicate:
https://developer.android.com/about/versions/11/privacy/storage
I just wanted to help because it seams that nobody has required time to work on it, and as it was mentioned by an user on the issue #973 this will be more problematic with client verification in TT 5.14 if we can't import a .tt file. Sorry for the inconvenient.

**Comment by beqabeqa473** [comment]
@bear101, if we implement all files access, would you able to fill a
Permissions Declaration Form on google play?

it is quick solution which sould work but not so recommended by google.
There are other ways to fix that but it requires more time and deep
testing that i personally don't have at the moment.

On 6/12/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> Closed #1923.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1923#event-9498008661
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
If TeamTalk requests full file system access then I think people wouldn't dare to install it. At least I would never install such an app on my phone. There must be a simpler way to load and save a file on Android.

**Comment by beqabeqa473** [comment]
Android even in all files access mode doesn't allow an app to view all
files, it doesn't allow an app to access other app related files,
everything in android/data is inaccessible also. So it is not ment to
acces everything on filesystem

On 6/13/23, Beqa Gozalishvili ***@***.***> wrote:
> Yes, there is better way but not with direct path access and teamtalk
> is not able to get and give bytes
>
> On 6/12/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
>> If TeamTalk requests full file system access then I think people wouldn't
>> dare to install it. At least I would never install such an app on my
>> phone.
>> There must be a simpler way to load and save a file on Android.
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/BearWare/TeamTalk5/pull/1923#issuecomment-1587809049
>> You are receiving this because you commented.
>>
>> Message ID: ***@***.***>
>
>
> --
> with best regards Beqa Gozalishvili
> Tell: +995593454005
> Email: ***@***.***
> Web: https://gozaltech.org
> Skype: beqabeqa473
> Telegram: https://t.me/gozaltech
> facebook: https://facebook.com/gozaltech
> twitter: https://twitter.com/beqabeqa473
> Instagram: https://instagram.com/beqa.gozalishvili
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Pull request closed without merging**
