### PR TITLE
enabled change status option when not connected

### PR DESCRIPTION
**Pull request by amirmahdifard**
now users doesn't forced to connect to a server to modify their status message.

### CODE REVIEW

**Comment by CoBC** [comment]
As I said previously, this change isn't sufficient to do what you want. With this change if you try to change your status without be logged to any server, radio buttons and edit field in "change status" dialog are empty and not checked, and when you log in a server, you have a status of video transmission incorrectly added.

**Comment by amirmahdifard** [comment]
can you review it so i can push another commit to add your requested changes?

**Comment by amirmahdifard** [comment]
@CoBC i tryed this: if anything is needed, let me know, sorry if a little bad, because it is my first contribution: also, @bear101 please review and let me know what's needed next

**Comment by CoBC** [comment]
You only remove checks for automatic status changes, E.G. when idle or when video transmission become active. It's not the correct file you're trying to edit.
Anyway, I can't just make a review to explain how to do, as I said previously, your request is a bit complicate to implement because we have to rewrite all change status dialog.
Sorry, but if you can't test your changes, it's not a good thing to open PR
@bear101 For now I'm in favour of closing this

**Pull request closed without merging**
