### PR TITLE
Use 'Delete' key to delete user account and server list entry

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Review by CoBC — CHANGES_REQUESTED** [review]
I suggest to use Shift+Delete instead of just Delete, to be more logical with existing deleting action for files list for example which use SHift+Delete

**Comment by bear101** [comment]
I see Delete-key as the intuitive way to delete. I wouldn't expect to use Shift-Delete.

E.g. Thunderbird use Delete-key to delete focused message. Not Shift-Delete.

**Comment by CoBC** [comment]
In this case, maybe change also shortcut to delete file to just delete 
instead of Shift-Delete. Just to uniformize shortcuts.

**Comment by bear101** [comment]
Won't this invoke "Delete File" from "User Accounts" dialog and when editing text?

**Comment by CoBC** [comment]
We can disable action associated with files in files list don't have 
focus, right?

**Comment by bear101** [comment]
I don't know. I think it will cause problems if you use Delete-key directly. I think it will be processed differently if it's hooked to a menu-item as keyboard shortcut.

**Comment by CoBC** [comment]
Hmmm, OK, so just keep like this for now :)

**Pull request merged**
