### PR TITLE
Ability to customize event messages

### PR DESCRIPTION
**Pull request by CoBC**
Add a new tab in preferences to customize status and TTS messages for events.

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC The label in the tab takes up too much space. Shouldn't we just have the text in the edit box and reset it to default if it's blank?

**Comment by CoBC** [comment]
Don't understand which label takes too much place? Which label do you 
want to remove?

**Comment by bear101** [comment]
The "Available variables..." label in "Events Tab"

**Comment by bear101** [comment]
Alternatively these Event messages could show up in a QInputDialog when the Text-To-Speech message is checked in "Text to Speech" tab.

**Comment by bear101** [comment]
If you later want to have more customizable status messages then there's no more space.

**Comment by CoBC** [comment]
Yes, I also thought of the alternative option to customize message when 
checking each event in TTS tab, but what about message use in TTS and 
status (chat history)?

**Comment by bear101** [comment]
Status messages already have a separate dialog in Display->Show statusbar events. So their customisation could happen there.

**Comment by CoBC** [comment]
OK, so I'll try and make another PR more later. I'll close it for now as 
the current implementation is not retained

**Comment by CoBC** [comment]
No problem :), we can try and find a better solution :)

**Comment by peter1384** [comment]
@CoBC anyway, i don't think customising these events would have a lot of points and usage, the default customisation is fine i guess, so your time could be spent to add other useful things instead.

**Pull request closed without merging**
