### PR TITLE
Fix incorrect Modified date on user accounts

### PR DESCRIPTION
**Pull request by bear101**
Fixes time zones ahead of UTC

### CODE REVIEW

**Comment by bear101** [comment]
@lbk2907 can you try the server binaries from this build and see if they fix the issue

**Comment by lbk2907** [comment]
@bear101
May I know which build?

**Comment by bear101** [comment]
From here: https://github.com/BearWare/TeamTalk5/actions?query=branch%3Aissue-1394

**Comment by lbk2907** [comment]
Ok. I'll give it a try.

**Comment by lbk2907** [comment]
@bear101
It's fix. Thanks.

**Pull request merged**
