### PR TITLE
Choose language at first startup

### PR DESCRIPTION
**Pull request by CoBC**
@bear101 If you are agree with changes in this PR, can you look to make settings choose at first startup to directly take effects? For now we have to restart TT or open and close preferences to apply settings choose at first startup.

### CODE REVIEW

**Comment by bear101** [comment]
Hm, it's still not working with the main menu. It only works when using preferences.

**Comment by CoBC** [comment]
It works if we call retranslateui after switchlanguage. I can make a commit for this, unless you have a better idea?

**Comment by CoBC** [comment]
It's called in mainwindow.cpp at line 632. Not sure we can called this in switchLanguage() method directly.

**Comment by CoBC** [comment]
Yes, look good for me.

**Comment by CoBC** [comment]
It's called in mainwindow.cpp at line 632. Not sure we can called this 
in switchLanguage() method directly.

**Pull request merged**
