### PR TITLE
Updating the file with the Russian translation.

### PR DESCRIPTION
**Pull request by artem59k**
The latest localization version did not open in qt linguist. Now everything works.

### CODE REVIEW

**Comment by bear101** [comment]
The Russian.ts file has 249 unresolved conflicts. These must be resolved before it can be merged.

**Comment by bear101** [comment]
Search for <<<<<<< and replace with the correct translation.

**Comment by artem59k** [comment]
This file may be old, but it works in the Qt linguist program. There was an unknown error when reading a file in the program.

**Comment by bear101** [comment]
Russian.ts cannot be converted to Russian.qm until the conflicts have been resolved.

**Comment by bear101** [comment]
Looks better but there's still 6 conflicts marked with <<<<<<<

**Pull request closed without merging**
