### PR TITLE
Use QTableView on model based widget

### PR DESCRIPTION
**Pull request by CoBC**
@bear101 Is this one something OK for you?
If yes, I'll change it on other table model
I find this more logic to use QTableView for multicolumn widget
More, this widget doesn't require accessible text role anymore, we can navigate with arrow keys like any real table, which is more efficient for me.

### CODE REVIEW

**Comment by bear101** [comment]
The row height is quite big in QTableView compared to QTreeView but I can probably fix that. So go ahead and change to QTableView

**Comment by peter1384** [comment]
I don't know if this is expected for this for now because not complete or something, but with this my banned users items are announced like this with nvda when I press up and down arrow.
data item  selected  row 1
data item  selected  row 2

**Comment by CoBC** [comment]
It's just because the column you're navigating in is empty, so press 
right arrow and you'll see

**Comment by peter1384** [comment]
oh no, so for seeing all of the information of a ban such as creater, ban type, ban time and all others we have to press right arrow now? this is not good at all!

**Comment by CoBC** [comment]
Yes, it's exactly the goal of a table, on all tables I know, you have to 
navigate in it to see info.

Personally, I find it really more convinient to be able to quickly see 
the info I want, E.G. ban type, instead of have to hear all previous info.

**Comment by CoBC** [comment]
I just pushed for online users. Unfortunately context menu actions seams to be broken :(
I'm searching why but if anyone has an idea before me, it will be really good :)

**Comment by peter1384** [comment]
then in this case personally i disagree with this and i don't know if i'd be able to use it properly because this is gonna be replaced by all tree views

**Comment by CoBC** [comment]
Sorry, but I don't really understand your problem with these changes

**Comment by peter1384** [comment]
my problem is that i have to press right arrow to view other info, but in tree view i could see everything
now i have to press right arrow to see username, ip, nickname, ban type, and this is gonna be replaced with everything, it's not comfurt, I didn't know the point of tables are this.

**Comment by CoBC** [comment]
And, if, for example, I want to see the ID of an online user, currently, 
I have to heard nickname, status message, IP, version, and more, before 
the ID, I have the time to drink a cup of tea before hearing the info I 
want.

**Comment by CoBC** [comment]
All will be read on first column (accessible text role), and we can continue to navigate with arrow keys to only read other info
Hope everyone is happy with this behaviour

**Comment by ChrisDuffley** [comment]
Yes. Other than left/right arrow keys not navigating each column then this is exactly like how a list view would behave. At least by what you're saying here. I'll still have to figure out how I'll test this when I'm back at a computer again.

Thank you for this change, I also may want to hear only one column most of the time. Does first/multi-letter navigation still work in these elements and if so, what column is it based on?

**Comment by CoBC** [comment]
Yes, one letter key navigation works. It's based on first column, depending on table.

**Comment by CoBC** [comment]
Done for me, just online users context menu is still broken, but don't understand why for now

**Comment by ChrisDuffley** [comment]
Will that method change depending on sort (via Sort By...) or no, always by the first column?

**Comment by CoBC** [comment]
The based column is always the same, but depending on sort result order will change

**Comment by bear101** [comment]
@CoBC can you rebase with master branch to get a clean commit history?

**Comment by CoBC** [comment]
I've rebased. Not sure why Git is still showing 7 commits. Maybe I'm not a rebase expert :(

**Comment by bear101** [comment]
@CoBC Column 0 in server list shows "Name", "Users" and "Country" as rows. And also many empty rows. "Name", "Users" and "Country" are also in header of columns 1, 2, 3.

**Comment by bear101** [comment]
@CoBC Also header sizes are not correct width initially. I have to adjust each of them manually. Is there a way to have horizontalHeader() to manually set preferred sizes if the size is not already stored?

**Comment by CoBC** [comment]
Hmmmm, other dialogs don't have the same issue? Strange if server list 
is the only one with this issue.

For horizontalHeader, I have to check again the doc :)

**Comment by CoBC** [comment]
@bear101 what about resizeSection? Is not this emthod you want to set 
default size?

**Comment by CoBC** [comment]
I pushed a new commit, hope this helps to fix server list

**Comment by bear101** [comment]
@CoBC I'll clean up the commit history and do a force push

**Comment by bear101** [comment]
@CoBC Your old branch is available as tableview-old

**Comment by bear101** [comment]
@CoBC when you select a server in "Server List" dialog and press "Connect" button it has no effect.

**Comment by CoBC** [comment]
This issue is also present in master branch, right? In all case this 
button doesn't have any effect for me when I select an item on the tree, 
tab to connect button and than press space. So, does it works in master 
branch with mouse?

**Comment by bear101** [comment]
Hm, yes, on master branch it also has this issue. The issue is the same with and without mouse.

I guess it makes sense that the focus check fails when none of the lists are focused :(

**Comment by CoBC** [comment]
Yes, you're right. But, do you see any other easy way to connect the 
"Connect" button to an action without this focus check? Or maybe we have 
to add a 2nd "Connect" button?

**Comment by bear101** [comment]
Maybe the "Connect" button should check selection instead. If one list has an item selected then it chooses that one.

**Comment by CoBC** [comment]
Should I make this change in this PR now? Or are you working on 
something else on this PR and I'll open another PR for this fix later?

**Comment by bear101** [comment]
Should we just remove the "Connect" button? It's a bit ambiguous when both list views have selection.

Please make the change from master branch. I'm currently review the QTableView changes.

**Comment by CoBC** [comment]
Yes, I thought to the same thing, this "Connect" button is not really useful anymore, we have double click, enter key and context menu to connect, I'll remove it.

**Comment by bear101** [comment]
Is it ok that I enable row selection in all the table views? It's more logical than cell selection

User Accounts dialog is already like this:
```
         <property name="selectionBehavior">
          <enum>QAbstractItemView::SelectRows</enum>
         </property>
```

**Comment by CoBC** [comment]
Yes, it's OK

**Pull request merged**
