### PR TITLE
Context menu to ban list

### PR DESCRIPTION
**Pull request by CoBC**
* Ability to sort banned list
* Option to move users bitween list
* Ban time converted to local format

### CODE REVIEW

**Comment by peter1384** [comment]
nice! Then, these buttons
> button remove banned user
and
<button put back to banned users should be removed to simplyfy the dialog and context menu actions does the work of these buttons.

**Comment by peter1384** [comment]
the option in the unbanned tree view context menu stays unavailable even when an option is selected in it, lol because in the void of unbanned context menu, you say
    auto srcIndex = m_bannedproxy->mapToSource(ui.bannedTreeView->currentIndex());
    but you should say
        auto srcIndex = m_bannedproxy->mapToSource(ui.unbannedTreeView->currentIndex());
        lol

**Comment by CoBC** [comment]
Good try, but nope, it should be:
auto srcIndex = m_unbannedproxy->mapToSource(ui.unbannedTreeView->currentIndex());
Btw, I'm glad if my mistakes are so funny

**Comment by peter1384** [comment]
oh yeah! that unbanid one too
lol no, your mistakes are not funny, i just laughed because i felt we need some fun while working and stuf, and things happen.

**Comment by peter1384** [comment]
actually, a very nice suggestion! The ability to unban all banned users! hear's how to
these >button and <buttons should not be removed, instead their job should be difrent.
When klicking this >button remove banned user, all items inside banned tree view should be moved to unbanned tree view
and when klicking this <button put back to banned users, all items inside unbanned tree view should be moved to banned tree view, wether they have only 1 item or 10000 items in them, these buttons should move them all
so this is an ability for server owners who have banned a lot of users from their servers and they just want to unban everybody.
But you'll need to wright 2 new voids for these buttons because currently we don't have any void that moves all items of one tree view to another tree view.

**Comment by CoBC** [comment]
Just press CTRL+A in the tree view and than press the button

**Comment by peter1384** [comment]
also, currently, pressing enter key in tree views just exits the dialog, but double klick in an item in banned tree view moves that user to unbanned tree view, and double klick on an item in unbanned tree view moves that item to banned tree view, So, enter key should do that as wel in tree views. Thanks!

**Comment by peter1384** [comment]
like the user accounts dialog, wich enter key does the double klick's job instead of doing unexpected things

**Comment by peter1384** [comment]
i don't think i have the ability to push commits to this branch to help you, if i could i'd do some things that i know how to do
currently, we have a place where it says pressing enter on the text box slot new ban, can we add 2 more elses to that lojic for tree views, or we need to wright it difrently, because it's nice and quick to press enter on an item in the tree view to move that item to the other tree view, also that's what double klick does see this
    connect(ui.bannedTreeView, &QTreeView::doubleClicked, this, &BannedUsersDlg::slotUnbanUser);
    connect(ui.unbannedTreeView, &QTreeView::doubleClicked, this, &BannedUsersDlg::slotBanUser);

**Comment by CoBC** [comment]
You don't have right to push on this repo
I've applied your suggestion

**Comment by peter1384** [comment]
ok then thanks. Then if anything else was good as a suggestion i'll let you know hear so you can aply

**Comment by peter1384** [comment]
it doesn't work. I just built the last commit. pressing enter on the tree views just exits the dialog, actually not only tree views, pressing enter anywhere exits the dialog.
may be there is a bug somewhere else, because for example when we pressed enter on user accounts dialog it didn't exit the dialog.

**Comment by CoBC** [comment]
I'm not a big fan of event filter but it seams we don't have choice for trees :(

**Comment by bear101** [comment]
There's a good deal of conflicts with the "search banned users" PR

**Comment by CoBC** [comment]
I think I've fixed it

**Comment by bear101** [comment]
The search function using "Enter" key is no longer working with this change

**Comment by peter1384** [comment]
oh, i understand why. The enter key we modifyed it so that it'll add or remove ban in tree views doesn't incclood that search thing hear, so it'll be fixed if you also inclood that when pressed enter on search text box do that

**Comment by bear101** [comment]
Replaced by #2312

**Pull request closed without merging**
