### PR TITLE
Favor UserAccount.szInitChannel over user's stored join setting

### PR DESCRIPTION
**Pull request by bear101**
This fixes issue described in #1020.

This can easily break something but it simplifies the join process. Basically szInitChannel should take priority over user's stored setting and is otherwise treated the same with regard to channel creation. I.e. if parent existing then create a new channel. Previous szInitChannel only worked if the channel already existed.

### CODE REVIEW

**Comment by Oreonan** [comment]
For me #1020 isn't fixed by this PR. If I edit an account to join an hidden channel, and I connect with this account (user account without right to sse hidden channel), no channel is joined.

**Comment by bear101** [comment]
Ah, I didn't have a '/' in the end when I tested yesterday. This cause subchannels with no name. I've fix this now.

**Comment by Oreonan** [comment]
OK, this point it's OK for me now. I'll test with temporary channels tomorrow and make a review after that.

**Review by Oreonan — APPROVED** [review]
Seems to be working as expected in all situations now. I guess change log need to be updated, and all will be OK.

**Pull request merged**
