### PR TITLE
Ability to show password in server list

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by bear101** [comment]
Shouldn't channel password also have a "Show password" checkbox?

**Comment by CoBC** [comment]
Done! I hope I didn't again break the GUI :)

**Comment by bear101** [comment]
@CoBC notice how the checkbox toggle can be done with a one-liner:
`connect(ui.chanpasswordChkBox, &QAbstractButton::clicked, this, [&](bool checked) { ui.chanpasswdEdit->setEchoMode(checked ? QLineEdit::Normal : QLineEdit::Password); } );
`

**Comment by bear101** [comment]
Here's a good article on lambda expressions in Qt: https://medium.com/genymobile/how-c-lambda-expressions-can-improve-your-qt-code-8cd524f4ed9f
The article also has a section called "Using lambdas instead of QObject::sender()"

**Comment by CoBC** [comment]
Thanks a lot :). I'll go read it.

**Pull request merged**
