### PR TITLE
croatian translation for teamtalk 5.4 android

### PR DESCRIPTION
**Pull request by zstanecic**
ignore the translation inm the e-mail. i've made some fixes here...

### CODE REVIEW

**Comment by bear101** [comment]
Hm, it's says Croatian translation, but the files changed are Hungarian. Anyway I'll merge the translation.

**Comment by zstanecic** [comment]
If it writes hu, please correct it to HR

**Comment by bear101** [comment]
Hm, -hr is Croatian. I thought it was Hungarian.

**Comment by bear101** [comment]
Ok, it will be included in the v5.4 release.

**Pull request merged**
