### PR TITLE
Only use QLabel in User info dialog

### PR DESCRIPTION
**Pull request by CoBC**
Maybe usage of readonly QLineEdit was wanted, but I didn't see the real advantage of it.
So, I just replaced it by static QLabel

### CODE REVIEW

**Comment by CoBC** [comment]
We can use arrow keysto navigate in a QLabel, but it's not read by 
screenreader, right. It's an issue which have to be reported to Qt.

However, note that we can use screenreader option to read character by 
character, E.G. with NVDA, numpad 3 and numpad 1.

**Comment by bear101** [comment]
The reason for QLineEdit was to be able to copy/paste user information. But it looks like it also works with QLabel.

**Comment by CoBC** [comment]
Yes it works, I find it more appropriate when we just display info

**Comment by jeremyp3** [comment]
@bear101 I find that this pr degrades the accessibility of this dialog box, as indicated in my first message, I don't understand the merge.

**Pull request merged**
