### PR TITLE
Redesign hostmanager

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by CoBC** [comment]
@bear101 Don't understand why when we try to remove a recent host, all next hosts are also removed :(
All the rest look good to me, you can review it :)

**Comment by CoBC** [comment]
Yes, I mixed some methods. The older deleteLatestHost method seems to didn't have never work in reality :(

**Comment by bear101** [comment]
ok, I'll look at it tomorrow. Then you still have more time for corrections :I

**Comment by amirmahdifard** [comment]
@CoBC hi
now that you are working on a new host manager, can you also add last joined channel checkbox ability?

**Comment by amirmahdifard** [comment]
https://github.com/BearWare/TeamTalk5/issues/1941

**Pull request merged**
