### PR TITLE
Update Chinese translation.

### PR DESCRIPTION
**Pull request by hejiadong0608**

### CODE REVIEW

**Comment by bear101** [comment]
Thanks for the translation. I still need several of the strings mentioned in #407. I hope to get around to it eventually.

**Comment by hejiadong0608** [comment]
Hello.
I don't know the ID of these strings. How can I get these IDs?
Thank you!
@bear101

**Comment by bear101** [comment]
If you open the new English.lng file you'll get the new IDs. Otherwise look in this commit: 2d986d2b17d7caa8653692748df4d5d5959f02bf

**Comment by hejiadong0608** [comment]
These new IDs are already included in this pull request. But there are many more strings memtioned in #407 
that are not included in new English.lng.
@bear101

**Pull request merged**
