### PR TITLE
Updated Turkish for new strings

### PR DESCRIPTION
**Pull request by OzancanKaratas**

### CODE REVIEW

**Comment by bear101** [comment]
Thanks @OzancanKaratas

**Comment by bear101** [comment]
you're fast :)

**Comment by bear101** [comment]
I'll send out a new beta (build 3) shortly. The new translation will, however, not be available until build 4.

**Comment by OzancanKaratas** [comment]
Yes, I enjoy to work with you. :)
However, should be included the new translations.

**Comment by OzancanKaratas** [comment]
Bjoern, please include info.plist into localizable content. Also, can you add a translator section in Version Information header?

**Comment by bear101** [comment]
You mean like a "Translated by" cell item?

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by OzancanKaratas** [comment]
Yes.

**Pull request merged**
