### PR TITLE
File size now converted using Qt functions to support more size 

### PR DESCRIPTION
**Pull request by jeremyp3**
Suite of modification for fix #1730 I had only modified the accessibility part in my previous PR

### CODE REVIEW

**Comment by CoBC** [comment]
@bear101 to avoid this kind of mistake in the future, I think we should use text already displayed in tree columns to build accessibility text. What do you think?

**Comment by jeremyp3** [comment]
thanks @CoBC for assistance!

**Review by CoBC — APPROVED** [review]
Look good to me!

**Comment by bear101** [comment]
Superseded by #1815

**Pull request closed without merging**
