### PR TITLE
Replace radio button by comboboxes in some dialogs

### PR DESCRIPTION
**Pull request by CoBC**
An user request was made to replace radio button by comboboxes.
@bear101 Is it OK? If yes, I can continue

### CODE REVIEW

**Comment by bear101** [comment]
I'm fine with this change but maybe we should release what we have now before merging it. What do you think?

One annoying thing at the moment is that Qt has mistakenly specified Qt 6.8beta2 as Qt 6.9 on Windows (if you check About box).

**Comment by CoBC** [comment]
OK to release current changes before merging new ones.

Qt 6.8 Beta 3 should be release tuesday: 
https://wiki.qt.io/Qt_6.8_Release so we can maybe release the new 
release in this new beta which hopefuly will fix this mistake.

**Comment by amirmahdifard** [comment]
my opinion is to also inclood only this change in 5.17 because our focus is on accessibility, and this change makes the accessibility of selections of these dialogs better. my opinion

**Comment by bear101** [comment]
@CoBC if you select DirectSound in Preferences and press Ok and then return to Sound System in Preferences dialog. Then sound devices will appear twice.

**Comment by CoBC** [comment]
@bear101 Qt 6.8 Beta 3 has been released. So I think you can update to 
this beta and than release the V5.17

**Comment by bear101** [comment]
@CoBC I've created the v5.17 release and uploaded it here: https://bearware.dk/teamtalk/v5.17/

There's some documentation that needs to be updated but I think we should release anyway. Then we can update the docs when we have more feedback.

**Comment by CoBC** [comment]
@bear101 Yes, I think we can update docs later. We just have to remember 
this point :)

**Pull request merged**
