### PR TITLE
Updated Turkish

### PR DESCRIPTION
**Pull request by OzancanKaratas**

### CODE REVIEW

**Comment by bear101** [comment]
thanks @OzancanKaratas! Btw, I've just come home from a one week holiday in Turkey :)

**Comment by OzancanKaratas** [comment]
Aaaaa, have you gone which city?

**Comment by bear101** [comment]
I went to Northen Cypres. It was nice to get away from the horrible Danish weather :)

**Comment by bear101** [comment]
But I've been to Turkey several times.. Istanbul, Izmir and Antalya.

**Comment by OzancanKaratas** [comment]
Hmmm. Kayseri is waiting for you :)
In the meantime, 49th string should be changed in the iTeamTalk. Because impossible to understand it. Also Version Information title and all its content isn't found into localization files. I think you need to run the script :)

**Pull request merged**
