### PR TITLE
some work on change log.txt

### PR DESCRIPTION
**Pull request by amirmahdifard**
this is just a test

### CODE REVIEW

**Comment by amirmahdifard** [comment]
oops, what happened to my branch then?

**Comment by amirmahdifard** [comment]
i changed some stuf in change log, but when i opened my pull request, it appeared as this: please help me: i'm lurning how to open pull request.

**Comment by amirmahdifard** [comment]
i called my branch changelogfix, but it doesn't have my branch on it: wy? is because i'm not a contributer?

**Comment by CoBC** [comment]
It seems you are trying to work on my repo, and you haven't right for this. You have to create a fork of bearware/teamtalk5 if you want to work on your own repo and you'll be able to create branches.

**Comment by amirmahdifard** [comment]
@CoBC ok thanks, can you tell me who to make my own fork?

**Comment by CoBC** [comment]
Go to repo's homepage and you'll see a button to fork

**Comment by amirmahdifard** [comment]
@CoBC ok thanks, i will try it: so bro, can you please reply that tikit about stream tts event thing? i answered you in there, so please if you don't want to do it or you want to do it, please answer if possible, because i asume that you already saw me and that person's comments: again thanks in advance.

**Pull request closed without merging**
