### PR TITLE
Split Display-tab in Preferences dialog into group boxes

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by CoBC** [comment]
@bear101 Shouldn't also hide label_4?
Also, do you see other widgets we can allow to show/hide?

**Comment by bear101** [comment]
Yes, you can hide the voice activation label (label4). Maybe also rename it to something more expressive.

If VU-meter updates are disabled then we can also hide that label.

**Comment by bear101** [comment]
@CoBC you can mark it is ready when you've finished your changes.

**Comment by CoBC** [comment]
I think we can already merge this one. Some work will be done in #2349
Also, do you think it can be good to allow hide some tabs like desktop and video?

**Comment by bear101** [comment]
I'd rather keep desktop and video tabs since they provide easy access to start/stop video/desktops.

**Comment by CoBC** [comment]
OK

**Pull request merged**
