### PR TITLE
Option to display server's message of the day in a welcome dialog box

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by HanaDadfar** [comment]
wow! nice work and good done. How can i get a built to try out this new feature?

**Comment by CoBC** [comment]
I built a client and you can download it here: https://corentin.bacque-cazenave.fr/TT_Test.zip
Also you can just wait for an official beta build later by @bear101

**Comment by HanaDadfar** [comment]
@CoBC ok, thanks. This repo doesn't have any tool to automaticly build when a new pr opens?

**Comment by HanaDadfar** [comment]
@CoBC a question: can teamtalk be built with Visual Studio 2022 comunity as whell, if so, i swich from 2019 to 2022

**Comment by CoBC** [comment]
Don't know, I'm using Visual Studio community 2019.

Maybe @bear101 have the answer

**Comment by HanaDadfar** [comment]
@bear101 i only have time until saterday to do this swich. So can you please tell me can teamtalk be built with v studio 2022 comunity also? or only 2019? thanks.

**Comment by HanaDadfar** [comment]
@CoBC hi,
do you know that why when i'm building teamtalk, my built client doesn't have any tts support, the tts is not working i mean. When i set the text to speech engin as talk and i press tab, i just reach to ok button. I did everything as teamtalk wish in the build, but i don't know why this is happening. Can you tell me?

**Comment by CoBC** [comment]
You have to put tolk.dll in the TT folder

**Comment by HanaDadfar** [comment]
tolk.dll is in the folder. The teamtalk5.exe which is built by teamtalk works fine with it, but my built teamtalk5.exe doesn't work with it. Why?

**Comment by HanaDadfar** [comment]
@CoBC i'm sorry, i have nowhere else to ask this question, so, if you can, please kindely help me resolv this problem, i wish to become a teamtalk contributor

**Comment by HanaDadfar** [comment]
@CoBC i haven't done anything rong. I follow teamtalk build instructions step by step exactly and i build, but i face this problem that teamtalk doesn't care about the tolk.dll file that is there.

**Pull request merged**
