### PR TITLE
Android client. Fixed some functions which will be explaned in the discription

### PR DESCRIPTION
**Pull request by peter1384**
fixed the navigate up button's problem, which now allowes you to interact with the root channel properly like other subchannels also, like windows client.
since android users now have access to the root channel, Fixed a bug that was preventing long presses on the root channel, Which means they can long press on the root channel and move users to the root channel as they can do with other channels
Also, as another direct result and some other related code fixes i've made, It is now possible only for admins to upload files to the channels they have not joined, inclooding the root channel, This had happened because in the teamtalk5's erules, i've read that only administrator accounts can upload files to the channels they have not joined. Note that default accounts cannot do that, The server disallowes that and they will get an error message if they try to do that.

### CODE REVIEW

**Comment by beqabeqa473** [comment]
split up fixes to separate commits please

On 3/15/24, peter1384 ***@***.***> wrote:
> fixed the navigate up button&#39;s problem, which now allowes you to
> interact with the root channel properly like other subchannels also, like
> windows client.
> since android users now have access to the root channel, Fixed a bug that
> was preventing long presses on the root channel, Which means they can long
> press on the root channel and move users to the root channel as they can do
> with other channels
> Also, as another direct result and some other related code fixes i&#39;ve
> made, It is now possible only for admins to upload files to the channels
> they have not joined, inclooding the root channel, This had happened because
> in the teamtalk5&#39;s erules, i&#39;ve read that only administrator
> accounts can upload files to the channels they have not joined. Note that
> default accounts cannot do that, The server disallowes that and they will
> get an error message if they try to do that.
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/BearWare/TeamTalk5/pull/2209
>
> -- Commit Summary --
>
>   * fixes some functions which fixes a fue bugs as a direct result
>
> -- File Changes --
>
>     M ChangeLog.txt (3)
>     M Client/TeamTalkAndroid/src/main/java/dk/bearware/gui/MainActivity.java
> (31)
>
> -- Patch Links --
>
> https://github.com/BearWare/TeamTalk5/pull/2209.patch
> https://github.com/BearWare/TeamTalk5/pull/2209.diff
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/2209
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***&gt;
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
instead of disabling menu items why not stop showing them at all? Then there's more space.

**Comment by peter1384** [comment]
@bear101 yes exactly i've already done what you said hear, All of them are setEnabled.setVisible to not show them at all, to have more space. You can build it and look at it, This is installed on my phone and I can see that they are not shown at all, Which is exactly what you want.

**Comment by peter1384** [comment]
@beqabeqa473 If i'm doing something, I have a reason for it. These commits cannot be split up because these commits with out each other are meaningless.
For example, If i fixed the move function in one commit, It's stil broken because navigate up's problem is not resolved.
So, I can't split up these commits because they are related and depending on each other. You can just look at the dif.

**Comment by peter1384** [comment]
this fixes https://github.com/BearWare/TeamTalk5/issues/2198

**Comment by bear101** [comment]
@peter1384 Please split the commits into two pull requests, so I can edit the commit messages.

**Comment by peter1384** [comment]
@bear101 as i said before, I can't split up these commits because they are related to each other, and one of them won't work with out the another one, And this pull request only modifys one file, Which is main_activity.java.
now, please tell me what do you want me to change in this pr and i will do it, but i won't be able to recreate this pr because i don't have an stable internet to fork this repo and clone it again and do everything from scrach.
but i've made sure that this pull request is ready and it does not cause any problems, so, you can look at the dif first to see what did i do in the code, And then you can build it and install it on your phone so you can see everything works as expected, And then you can merge this pull request. Or if you want something to be added or removed, you can let me know, and i will do it

**Comment by peter1384** [comment]
once this pull request is merged, I'm gonna start to fix somethings about the last joined channel checkbox function, And after that, I'm gonna develop transmit controles, Which was requested for a long time!
Kind regards.

**Comment by peter1384** [comment]
@bear101 i can open these commits in difrent pull requests, but i didn't think that it's needed because these commits are related to each other, but i will do it.

**Pull request closed without merging**
