### PR TITLE
Event handling in python wrapper

### PR DESCRIPTION
**Pull request by beqabeqa473**
This pr adds event handling possibility to be used by client developers in python.

### CODE REVIEW

**Comment by bear101** [comment]
Isn't it possible to run the event loop as a timer in the main-thread? Introducing threading causes all sorts of concurrency problems.

**Comment by beqabeqa473** [comment]
I think it will block main eventloop if using this library with toolkit like wx.
Do you have an idea how t odo it without blocking execution?

On 9/16/22, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> Isn't it possible to run the event loop as a timer in the main-thread?
> Introducing threading causes all sorts of concurrency problems.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1497#issuecomment-1248935649
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by beqabeqa473** [comment]
We need a way two loops to work together.
This might be possible in some cases by introducing asyncio pattern in
the library, but this brings more complications.

On 9/16/22, Beqa Gozalishvili ***@***.***> wrote:
> I think it will block main eventloop if using this library with toolkit like
> wx.
> Do you have an idea how t odo it without blocking execution?
>
> On 9/16/22, Bjørn Damstedt Rasmussen ***@***.***> wrote:
>> Isn't it possible to run the event loop as a timer in the main-thread?
>> Introducing threading causes all sorts of concurrency problems.
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/BearWare/TeamTalk5/pull/1497#issuecomment-1248935649
>> You are receiving this because you authored the thread.
>>
>> Message ID: ***@***.***>
>
>
> --
> with best regards Beqa Gozalishvili
> Tell: +995593454005
> Email: ***@***.***
> Web: https://gozaltech.org
> Skype: beqabeqa473
> Telegram: https://t.me/gozaltech
> facebook: https://facebook.com/gozaltech
> twitter: https://twitter.com/beqabeqa473
> Instagram: https://instagram.com/beqa.gozalishvili
>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
I would suggest you rename `def _ttEventLoop(self)` to `def runEventLoop(self)` and remove the "while true". Then it's up to the user whether to spawn a thread.

**Comment by bear101** [comment]
That's how the Java wrapper classes is designed

**Comment by beqabeqa473** [comment]
Ok, done.

On 9/16/22, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> That's how the Java wrapper classes is designed
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/1497#issuecomment-1248969702
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Pull request merged**
