### PR TITLE
Change way to display number of characters for messages

### PR DESCRIPTION
**Pull request by Oreonan**
@bear101 If you are agree with this approach, I can also modify in main window. The GUI has probably to be reviewed also.
@beqabeqa473 Is this approach better for you?

### CODE REVIEW

**Comment by bear101** [comment]
@Oreonan Instead of displaying the number of characters, can't we show a dialog if the number is exceeded? There's not really room for this extra label on the mainwindow

**Comment by bear101** [comment]
And display exceeded by how much

**Comment by Oreonan** [comment]
Did you mean add a dialog if limit is exceeded hen sending the message? 
And in case the limit is exceeded I guess we should keep the text in new 
message field?

**Comment by bear101** [comment]
Yes, keep the text and not send until the user has reduced it

**Comment by bear101** [comment]
Unfortunately I never managed to fix #412 so messages can be trimmed correctly. I wonder if new versions of C++ library has a way to trim UTF-8 strings.

**Comment by beqabeqa473** [comment]
hi all.

It is better now, but i think displaying exceeded limit by number of bytes is not accurate, because user may don't know that emoji is 4 bytes size, if exceeded limit is 520 characters, and they are removing last char, which is sized by 4 bytes, an app wiill tell them that exceeded limit now is 516 characters which is wrong from ux point of view.

What do you think about that?

**Pull request merged**
