### PR TITLE
Build TeamTalk for Ubuntu 24

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC did you manage to build TeamTalk for Ubuntu 24? I cannot make Qt 6 find Qt TextToSpeech.

**Comment by CoBC** [comment]
I only tried with manual install of Qt 6 on Debian with @jeremyp3
I just saw Ubuntu 24.04 has Qt 6.4 and qt-speech-dev:
https://packages.ubuntu.com/noble/ppc64el/libs/qt6-speech-dev
I'll try on Ubuntu directly

**Comment by bear101** [comment]
Hm, also WebRTC doesn't compile on Ubuntu 24. There's some Python errors:
```
[0:00:43] Finished running: git rev-parse --verify HEAD
----------------------------------------
Error: 1> Key 'deps' error:
1> Key 'src/third_party/test_fonts/test_fonts' error:
1> Or(None, <class 'str'>, <function _NodeDictSchema.<locals>.validate at 0x7f9cfb53f790>, <function _NodeDictSchema.<locals>.validate at 0x7f9cfb53f8b0>) did not validate {'dep_type': 'gcs', 'condition': 'non_git_source', 'bucket': 'chromium-fonts', 'objects': [{'object_name': 'f26f29c9d3bfae588207bbc9762de8d142e58935c62a86f67332819b15203b35', 'sha256sum': 'f26f29c9d3bfae588207bbc9762de8d142e58935c62a86f67332819b15203b35', 'size_bytes': 32750602, 'generation': 1717109450425063}]}
1> Missing keys: 'packages'
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "name": "src",
    "url": "https://webrtc.googlesource.com/src.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --nohooks --with_branch_heads
Subprocess failed with return code 1.

```

**Comment by CoBC** [comment]
Same issue with Qt TextToSpeech due to a dependency of Qt6QmlIntegrations.
Did you manage to solve the issue regarding this QtSpeech issue?

**Comment by bear101** [comment]
No, not yet. It's just a matter of finding the right package.

**Comment by jeremyp3** [comment]
concerning the qt-speech error, you need to install the package "qt6-declarative-dev"

**Comment by CoBC** [comment]
For WebRTC, it seams installing gclient can help. Some errors are still present but we can continue a bit...

**Pull request merged**
