### PR TITLE
Multi selection in banned users dialog

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Review by CoBC — COMMENTED** [review]
Looks good, however I have 2 feedback:
- Shouldn't show all IP or username of selected users in text box?
- Do you see any way to indicates in an accessible mode (maybe modify accessible text role) if an user is selected or not in the tree?

**Comment by bear101** [comment]
The idea of the text box is to quickly modify an existing ban. So e.g. change "192.168.0.100" to "192.168.0.0/24" so a subnet is be banned. Spammers typically use an entire subnet.

**Comment by bear101** [comment]
W.r.t. selection then the model cannot tell if an item is selected. I've tried looking in "Online Users" and "User Accounts" dialog and also there is not a way to indicate selection.

Maybe we should do a TTS event in BannedUsersDlg::banSelectionChanged ?

**Comment by CoBC** [comment]
> W.r.t. selection then the model cannot tell if an item is selected. I've tried looking in "Online Users" and "User Accounts" dialog and also there is not a way to indicate selection.
> 
> Maybe we should do a TTS event in BannedUsersDlg::banSelectionChanged ?

Yes, it's probably the best way

**Pull request merged**
