### PR TITLE
added user id to android client user prop

### PR DESCRIPTION
**Pull request by peter1384**

### CODE REVIEW

**Comment by peter1384** [comment]
@bear101 I don't know why this doesn't compile, i've done everything for it that was needed for this to work. Can you please look and tell me?

**Comment by bear101** [comment]
Please finish your merge requests. I don't plan to do it.

**Comment by peter1384** [comment]
@bear101 i'll finish it my self, just i'v done everything properly, but it doesn't compile, it gives an error called faled to link rezorses file

**Comment by beqabeqa473** [comment]
Here is not a learning centre.

Programming is not based on trials and errors, so go ahead and study and return back to it when you will have understanding how things work.

**Comment by peter1384** [comment]
@beqabeqa473 and here is not a personal attacking place. So, kindely stop your fighting, because i will not allow you to talk to me like that.
thanks.

**Comment by peter1384** [comment]
for now i'm closing this, i'll develop it better later. For now i'll be working something else

**Pull request closed without merging**
