### PR TITLE
Don't play sound for our channel messages

### PR DESCRIPTION
**Pull request by Oreonan**
Uniformize behavior bitween channel and private messages

### CODE REVIEW

**Comment by bear101** [comment]
I guess this should also be the case for Qt client?

**Comment by Oreonan** [comment]
@bear101 Yes, you are right, ef82ab7

**Comment by ChrisDuffley** [comment]
I much prefer the channel message sound being played  as there may be several people who have their TTS events turned off or their speech may be muted on its own for screen reader users. I strongly recommend leaving it as is.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Comment by Oreonan** [comment]
In fact, the idea is to standardize the behavior between channel 
messages and private messages, and therefore to leave the sound only for 
messages from other people than ourselves.

**Comment by ChrisDuffley** [comment]
O, that makes sense, thanks to the subject.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

**Pull request merged**
