### PR TITLE
Ignore limit text size in channels tree for screen readers

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by peter1384** [comment]
would you also please explane this? thanks

**Comment by bear101** [comment]
Doesn't the change remove the number of users part of the channel name? The parantesis part, e.g. "(4/6)"

**Comment by CoBC** [comment]
No, it doesn't, channel name, users count, channel topic, and potential 
emojis are added before accessible text role definition

**Comment by CoBC** [comment]
OK, I finally understood the issue, you're right, count was removed to display role with this change, so, I made a different string for display and accessible text roles

**Comment by peter1384** [comment]
i've built this, and i haven't noticed any changes in the channel tree with my screenreader. Can you please explane what does this pull request do? i'd like to know

**Comment by CoBC** [comment]
By default, text in channels tree (including channel name, channel 
topic...) are limited to 50 characters, this limit can be increase to 
512 characters in preferences. So, in this PR, I removed this limit for 
accessible text role, so SR always ahve entire item text available, and 
the limit only concerns display

**Comment by peter1384** [comment]
oh very nice! can't this 512 limits be removed or the ability to increace it to more than 512 characters for display users as wel? I think it would be a good idea

**Comment by CoBC** [comment]
Not sure a lot of screens support more than 512 characters per line

**Pull request merged**
