### PR TITLE
Place QSoundEffect in a queue until playback is finished

### LINKED ISSUE #2220: Sound Event Not Playing Correctly in "Default" Mode
### Description

There's an issue with the playback of sound events in the "Default" mode. The exact behavior is challenging to articulate, but generally, the correct sound isn't always triggered. Instead, the last played sound persists. For example, when User A connects to the server, the appropriate sound plays. However, subsequent events like User B sending a message to the channel result in the repeated playback of the initial connection sound rather than the expected channel message sound. This issue needs attention to ensure accurate sound playback.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I expected the sound events in the "Default" mode to play accurately and consistently according to their respective triggers. Specifically, when User A connects to the server, I anticipated hearing the designated sound associated with that event. Subsequently, when other events occur, such as User B sending a message to the channel, I expected to hear the corresponding sound without any interference from previously played sounds. Overall, I expected the sound playback to align precisely with the actions happening within the application, providing clear auditory feedback to users.

### Actual behavior

In the "Default" mode, the sound events are not playing as expected. When User A connects to the server, the designated sound associated with this event plays correctly. However, subsequent events, such as User B sending a message to the channel, do not trigger the intended sound. Instead, the sound that was played during User A's connection persists and is heard again, despite the occurrence of a different event. This results in inconsistent and inaccurate sound playback, which can lead to confusion among users regarding the actual events happening within the application.

### Steps to reproduce problem

I am unsure since which version of TeamTalk this issue has existed, but my current TeamTalk version is 5.15.2.5137 - Unreleased. All that is needed to reproduce the problem is to change the playback mode of the sound event to "Default".

### PR DESCRIPTION
**Pull request by bear101**
This fixes #2220

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC you can choose which one to merge

**Comment by CoBC** [comment]
I prefer this one but in this case shouldn't remove current one-by-one mode, merge #2243 to fixe #2220 and convert one-by--one mode to this method?

**Comment by bear101** [comment]
Default mode plays using Qt whereas the two other (Overlapping and One-By-One) plays on your selected TeamTalk sound device. I think we should stick to calling this new "Default".

**Comment by bear101** [comment]
The previous behaviour of Default works like #2243

**Comment by CoBC** [comment]
OK but in this case I think we should merge #2243 instead, because some 
users have habit with the way "default" mode play sounds, and can be 
confused if "default" goes to play like "one by one"

**Pull request closed without merging**
