### PR TITLE
Ubuntu 18 is EOL

### PR DESCRIPTION
**Pull request by bear101**
GitHub is no longer supporting Ubuntu 18 on April 1st 2023, so these commits removes support for building Ubuntu 18 on GitHub.

### CODE REVIEW

**Comment by Nardol** [comment]
What doe it imply for final releases on Debian? Will you still provide prebuilt binaries?
The Ubuntu 18 release is the only version which can run on Debian Buster and Bullseye, and it looks like the same for the future Debian Bookworm because of OpenSSL.

**Comment by bear101** [comment]
I'll still provide a TeamTalk Pro server for Ubuntu 18

**Comment by Nardol** [comment]
> I'll still provide a TeamTalk Pro server for Ubuntu 18

And about the client?
Which has the same behavior on Debian when trying to run the Ubuntu 20.04 version.

**Comment by bear101** [comment]
The client is bye bye

**Comment by bear101** [comment]
I cannot provide binaries for distributions that are no longer supported. There's also users who are complaining that TeamTalk no longer supports Windows XP. It's absurd.

**Comment by bear101** [comment]
PR #1780 also cannot build on Ubuntu 18 because the Qt version on Ubuntu 18 doesn't support TLS certificate information.

**Comment by Nardol** [comment]
> I cannot provide binaries for distributions that are no longer supported. There's also users who are complaining that TeamTalk no longer supports Windows XP. It's absurd.

But debian Buster is LTS and Bullseye is stable), so both still maintained.
If I totally agree with you on Windows, consequences are very different on Linux.

> PR #1780 also cannot build on Ubuntu 18 because the Qt version on Ubuntu 18 doesn't support TLS certificate information.

Which version supports it?
If I am correct, on Debian Buster we have QT 5.11.3 and Bullseye provides 5.15.2.

@jeremyp3 can you confirm?

**Comment by ChrisDuffley** [comment]
> I cannot provide binaries for distributions that are no longer supported. There's also users who are complaining that TeamTalk no longer supports Windows XP. It's absurd.



Yes, I agree with you here. Why on earth is anyone even still running XP with TeamTalk in the first place? That has not been supported for almost 10 years now...

As for Ubuntu 18/20, 20.04 LTS (which I run because of cPanel and WHM on my server) is not EOL until 2030. If this version is not maintained for TeamTalk, there's no way I can upgrade the binary and then run it, just with 20.04 alone, from how this looks.

Thanks.

**Comment by poretsky** [comment]
Ubuntu LTS releases life has been prolonged up to 10 years.

See https://ubuntu.com/esm for more information.

**Pull request merged**
