### PR TITLE
fixed compilation error

### PR DESCRIPTION
**Pull request by peter1384**
when corentin added the mytab files, he forgot to update the mainwindow.pri file and add the mytab cpp and h files in it, and that's why we got those compilation errors. It now has been fixed. So from now on, please when you add or remove a file, take care in mainwindow.pri also, So we don't get compilation errors Thanks

### CODE REVIEW

**Comment by peter1384** [comment]
fixes https://github.com/BearWare/TeamTalk5/issues/2383

**Comment by CoBC** [comment]
@bear101 As we previously discussed, QMake is deprecated, and mainwindow.pri should now contains only files relevant for translations, if I remember correctly.
So, I suggest to update readme.md with instructions to build using CMake instead of QMake.

**Comment by peter1384** [comment]
@CoBC
As I remember, Me And some people wer getting errors with cmake when getting the dependencys, And i'm not using cmake, I'm using qt creater to build teamtalk, and even with that out of the way, I don't know the cmake command to get teamtalk5.vcxproj in qt teamtalk folder, I follow these steps because I use qt creater.
Setup Qt Framework in PATH so we can use *qmake.exe* to generate
project files:

`# set PATH=C:\Qt\6.7.0\msvc2019-64\bin;%PATH%`

Generate project files for TeamTalk Qt-based client:

`# qmake -tp vc CONFIG+=release teamtalk5.pro`

Now open *TeamTalk5.vcxproj* in Visual Studio 2019 and build.
so, If qmake is removed, we'll be in troble. But if you really want to make things simpler for yourself, I'll make mainwindow.pri in a way that you don't need to update the files in it anymore, it will update its self automaticly, We won't call the files names anymore and will remove all of the files names from mainwindow.pri, and just say,
*.h, *.cpp, *.ui, /*.cpp, etc, As you did with the langs in your pr,
This way, We will be able to stil build with qmake, and you won't need to update the files in mainwindow.pri anymore.

**Comment by peter1384** [comment]
cmake will not work for those who use qt creater, So I disagree

**Comment by bear101** [comment]
qmake support has been removed. Please use CMake. The README.md file has been updated in QtTeamTalk folder

**Comment by peter1384** [comment]
heh. I'm sorry for this kind of development

**Pull request closed without merging**
