### PR TITLE
Server list export facility in Android client

### PR DESCRIPTION
**Pull request by poretsky**
AFAIK, it is just the feature in demand. Please consider it for the
upcoming release.

### CODE REVIEW

**Comment by bear101** [comment]
@poretsky some users have reported that the local saved servers sometimes disappear. Have you heard about this? I've only seen it if I uninstall the app (and I guess this is ok).

**Comment by poretsky** [comment]
No, I didn't hear about it, but, of course, if you uninstall the app,
account data may disappear since it is saved as app
preferences. Suggested feature can help in such cases and when accounts
should be transferred to the client installed on another device.

**Comment by beqabeqa473** [comment]
maybe we can somehow use android backup functionality to save tt
preferences in the cloud?

just a thought.

On 1/17/21, Igor B. Poretsky <notifications@github.com> wrote:
> No, I didn't hear about it, but, of course, if you uninstall the app,
> account data may disappear since it is saved as app
> preferences. Suggested feature can help in such cases and when accounts
> should be transferred to the client installed on another device.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/726#issuecomment-761750181


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by poretsky** [comment]
May be. As I see, backup is allowed in app manifest, thus, it should
be managed according to device settings. And, anyway, it would
apparently not be enough to transfer accounts, for instance, to a
Windows client.

**Comment by beqabeqa473** [comment]
yes, you are right.

anyway personally for me if we have import, why not to include export as well?

On 1/17/21, Igor B. Poretsky <notifications@github.com> wrote:
> May be. As I see, backup is allowed in app manifest, thus, it should
> be managed according to device settings. And, anyway, it would
> apparently not be enough to transfer accounts, for instance, to a
> Windows client.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/726#issuecomment-761754828


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
If I try to export the list I get an error that it cannot write to /storage/emulated/0/.... Is there a file permission missing?

**Comment by poretsky** [comment]
I suspect that it happens due to new
[storage access policy](https://developer.android.com/about/versions/11/privacy/storage)
introduced in recent Android versions. And this most likely affects file
transfer operations as well. So, I can suggest following options to
address this issue:

1) Reverting 75e0ef19.

2) Refactoring all file operations according to new rules.

3) Trying to request legacy behaviour via manifest.

Personally I'd prefer the first one since it is the simplest way to get
a guaranteed result.

**Pull request merged**
