### PR TITLE
Ability to customize timestamp format

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by peter1384** [comment]
what is timestamp? can you discribe please?

**Comment by CoBC** [comment]
Date and time in chat history, files list, user accounts, banned users

**Comment by bear101** [comment]
@CoBC should the QLineEdit and Variables button be disabled if "Timestamp" checkbox is unchecked?

**Comment by CoBC** [comment]
Probably not, because checkbox effect is only for chat history, but 
timestamp format is apply for all date and time (E.G. in file list, 
banned users dialog, user accounts dialog...)

**Comment by CoBC** [comment]
@bear101 Should we add a button to reset to default format? And, if yes, do we have place to add one more button in this tab? Display tab is very big :(

**Comment by bear101** [comment]
@CoBC can't blank field be default format?

**Comment by CoBC** [comment]
OK for blank field for default format, so it's already the case

**Pull request merged**
