### PR TITLE
Added missing _domoveUser function in TeamTalk5.py

### PR DESCRIPTION
**Pull request by DalisonCPU**
To create a function in an app, I had to use the DoMoveUser function that wasn't added, so I included it in "TeamTalk5.py".
OBS: Probably the amount of lines that show as changed is because there were carriage-return changes, of Linux to Windows.

### CODE REVIEW

**Comment by bear101** [comment]
Please look at your diff. Something has gone terribly wrong.

**Comment by yukie-nobuharu** [comment]
There are other functions missing from TeamTalkPy. please check this.
#1775

**Comment by DalisonCPU** [comment]
Instead of saying it's terrible, you can try to help people help you.

**Comment by DalisonCPU** [comment]
trying to help fix my git problem

**Comment by Nardol** [comment]
> OBS: Probably the amount of lines that show as changed is because there were carriage-return changes, of Linux to Windows.

Why not respecting these cariage returns which are probably the cause of your ugly diff?
Every good code editor let the choice to keep the actual cariage return.
Are you sure your code was really based on the last code revision in this repository?

I hop it is not from Chat-GPT (as it is the last tendance lol) because its information are not from after 2020 IIRC.

**Pull request closed without merging**
