### PR TITLE
update chinese translation for installer

### PR DESCRIPTION
**Pull request by hejiadong0608**

### CODE REVIEW

**Comment by CoBC** [comment]
Unfortunately the language file zh.isl doesn't exists so this will not work.
Maybe we can use the translation available at https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation for Chinese and then merge this PR with translated component names

**Comment by hejiadong0608** [comment]
@CoBC  I tried putting this file here, but I'm not sure if it will work.

**Comment by CoBC** [comment]
Yes it works. Can you just use zh_CN instead of chinesesimplified in teamtalk5.iss to be align with other languages?

**Comment by hejiadong0608** [comment]
@CoBC  OK i've finished it.

**Comment by CoBC** [comment]
OK, looks good to me

**Comment by bear101** [comment]
Shouldn't the Chinese translation be submitted to Inno Setup project?
https://github.com/jrsoftware/issrc/blob/main/CONTRIBUTING.md

**Comment by hejiadong0608** [comment]
@bear101 This Inno translation file is not mine, I submit it here just to make the TeamTalk installer support Chinese.

**Pull request merged**
