### PR TITLE
update chinese translation

### PR DESCRIPTION
**Pull request by hejiadong0608**

### CODE REVIEW

**Comment by bear101** [comment]
@hejiadong0608 Can you please use "git rebase" instead of "git merge". This pull request says it has 130 changes but it should only say there is 1 change.

**Comment by hejiadong0608** [comment]
@bear101  What should I do now?

**Comment by bear101** [comment]
You should write "git rebase upstream/master" instead og "git merge upstream/master". That is if you're using git from console. Then your latest git-commit will be the only difference from the official TeamTalk5-repo.

**Comment by hejiadong0608** [comment]
@bear101 OK.

**Pull request merged**
