### PR TITLE
add F6 key for switch text edit and history

### PR DESCRIPTION
**Pull request by jeremyp3**

### CODE REVIEW

**Comment by bear101** [comment]
@jeremyp3 Can you also put this feature in the documentation: Documentation/TeamTalk/userinterface.md

Otherwise people have no way of knowing.

**Comment by bear101** [comment]
On macOS I just get the change status dialog when pressing F6 in text message dialog

**Comment by CoBC** [comment]
This only appears first time "Text Message" dialog get focus, right? If you switch back to main window and then back again to text message dialog I think this issue doesn't appear anymore.

**Comment by bear101** [comment]
I get the "Change Status" dialog every time. Both on initial focus of "Text Message" dialog and switching back and forth

**Pull request merged**
