### PR TITLE
Remove QMake support

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by peter1384** [comment]
@bear101 why are you not considering qmake users? Can you please answer from now on how am i going to build qt teamtalk? I don't know the command and instructions to build with cmake. If it is important for you that people can stil build the client and contribute to the project, please answer this comment. Thanks

**Comment by amirmahdifard** [comment]
@bear101 something is unclear in your readme. you say setup qt framework in envirenment variables so cmake can detect qt, for example
which command is your example command and which command we should enter actually?

**Comment by amirmahdifard** [comment]
if you want to do this then ok but at least make the readme a bit clearer and more understandable

**Comment by CoBC** [comment]
@bear101 Shouldn't we also add instructions on how to generate only translations in readme?

**Comment by peter1384** [comment]
you should see these errors and fix them at least.
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR)
OpenSSL libcrypto.dll for Qt deployment found here: QT_OPENSSL_LIBCRYPTODLL_PATH-NOTFOUND
OpenSSL libssl.dll for Qt deployment found here: QT_OPENSSL_LIBSSLDLL_PATH-NOTFOUND
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done (8.0s)
-- Generating done (0.4s)
-- Build files have been written to: C:/TeamTalk5-qt-remove-qmake/Client/qtTeamTalk/builddir

C

**Pull request merged**
