### PR TITLE
Playback sound events using TT_InitLocalPlayback

### PR DESCRIPTION
**Pull request by bear101**
Three options to play sound events:

1. Use default OS playback
2. Use TeamTalk sound devices doing one-by-one playback
3. Use TeamTalk sound devices doing overlapping playback

### CODE REVIEW

**Comment by CoBC** [comment]
@bear101 The "One by one" option seems to not work as expected. For example try to quickly enable and disable voice activation when this option is selected, you only hear some sounds, and not all sounds one by one as expected.
Also, don't forget to link label_47 with sndeventPlaybackComboBox for accessibility :)

**Comment by bear101** [comment]
Please try again!

**Comment by CoBC** [comment]
Last thing, the volume is very different in default mode and in other modes, I set the volume to 13%, and it's much louder in default than in other modes. The rest looks fine to me now.

**Comment by bear101** [comment]
Volume of TeamTalk playback is controlled by master volume. Maybe that's why there's a big difference. Also if you mute master volume then you'll not hear playback.

**Comment by CoBC** [comment]
Oh yes, you're right.

**Review by CoBC — APPROVED** [review]

**Comment by jeremyp3** [comment]
@bear101 
under linux, in "one by one" mode the sound is cut while the sound is playing

**Comment by jeremyp3** [comment]
https://user-images.githubusercontent.com/30219507/200932928-bb888368-583b-41da-97a4-a82e33ff3bad.mp4

Here is an example of recording in attachment

**Pull request merged**
