### PR TITLE
Modifications to banning

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by amirmahdifard** [comment]
i really need the ban duration in the teamtalk: i hope it gets done a s a p

**Comment by bear101** [comment]
@CoBC I'll import the list of public VPNs, so be aware that the ban-list is going to be huge afterwards. We can, however, delete most of the existing bans, since their IPs are already in the list.

**Comment by bear101** [comment]
We can also block all data centers if we only want "real users" on the server. Should we do that as well?

**Comment by CoBC** [comment]
I suggest to do that as an option, if you're OK.

**Comment by beqabeqa473** [comment]
Hi Bjoern.

How about bots? if user wants to have a music bot in their channel?

On 10/19/23, Corentin Bacqué-Cazenave ***@***.***> wrote:
> I suggest to do that as an option, if you're OK.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/2053#issuecomment-1769291297
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Muamalaljanahi** [comment]
> We can also block all data centers if we only want "real users" on the server. Should we do that as well?

I don't think this is a good idea, because we usually host MusicBots on our virtual private server

**Comment by prince18d** [comment]
> > We can also block all data centers if we only want "real users" on the server. Should we do that as well?
> 
> I don't think this is a good idea, because we usually host MusicBots on our virtual private server

It is possible to bring bots via localhost or 127.0.0.1

**Pull request merged**
