### PR TITLE
Create info.txt

### PR DESCRIPTION
**Pull request by DevBDK**

### CODE REVIEW

**Comment by bear101** [comment]
Ah, yes, that's the way to do it.

**Comment by DevBDK** [comment]
Got it?

**Comment by bear101** [comment]
The example looks good. I can see it follows the Java example.

**Comment by bear101** [comment]
The file with the actual C-API calls is not there as far as I can see

**Comment by DevBDK** [comment]
Moin Bjoern,

did you see that now?

**Comment by DevBDK** [comment]
Something wrong with my Fork, it is not syncron to the master. I dont see the Folder what i created in the Master section. ?

**Comment by bear101** [comment]
As far as I can see you created a branch called DevBDK-TeamTalkServer.NET which contains the example you made. But the actual calls to TTS_* are missing. I guess they should be in TeamTalkInterop.cs

**Comment by DevBDK** [comment]
Hi Bjoern,

did u create the folder now at the master?  TeamTalkServer.NET, so then i can upload it direct to this location

**Comment by bear101** [comment]
The "inter-op" (C-API calls) should be be in TeamTalk.NET folder? Either 
in a separate file or in TeamTalkInterop.cs.

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Pull request merged**
