### PR TITLE
Updating russian language

### PR DESCRIPTION
**Pull request by artem59k**
Updating the Russian language. Added text-to-speech event strings. Translation missing gui lines.

### CODE REVIEW

**Comment by artem59k** [comment]
Added missing lines in GUI

**Comment by bear101** [comment]
@artem59k Thanks for the translation! There were a couple of conflicts that I've fixed. I'll update the translation on master branch, so you can get the latest changes.

**Comment by bear101** [comment]
@artem59k Please add your name to the translators [here](https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/languages/Russian.ts#L29). Just copy/paste the previous line and add your own name. I can also do it if you send me your name.

**Comment by bear101** [comment]
I've updated the translations on master branch now

**Pull request merged**
