### PR TITLE
Improve translations for classroom changes

### PR DESCRIPTION
**Pull request by CoBC**
It is required for some languages (included French) to have diferent strings for diferent contexts. So I introduced this changes here.

### CODE REVIEW

**Comment by bear101** [comment]
I'm ok with the change, but whether it works for all languages, I don't know.

Also it will be a bit difficult for translators to know what string will become %1 in this strings: "%1 channel messages!"

**Comment by CoBC** [comment]
We can maybe just add a comment for translators to explain the %1?

**Comment by bear101** [comment]
I've added comments to the translator and removed the "!" after each transmit type.

**Comment by bear101** [comment]
Comments are added like this: tr("%1 has to blah", "this is my comment")

**Comment by CoBC** [comment]
Look good for me

**Pull request merged**
