### PR TITLE
Translate installer

### PR DESCRIPTION
**Pull request by CoBC**
Just add French to see if it works. If it's OK, we can add more languages

### CODE REVIEW

**Comment by CoBC** [comment]
@bear101 Maybe we should find a way to integrate translations for component names
Do you think it's easy for translators to understand how to add translation directly to this InnoSetup script? Or should we ask known translators to send us translations and integrate the changes ourselves?

**Comment by bear101** [comment]
Yes, it works. I wonder if there's a way to just include all the languages that are automatically included with Inno Setup.

**Comment by CoBC** [comment]
Inno Setup examples include language one by one. Also we don't support 
all languages in TT, E.G. Inno Setup provide translation for Armenian 
but we don't have Armenian translation in TT, so IMO it make no sense to 
provide an installer in a language don't supported by the app

**Comment by CoBC** [comment]
I can add all languages we support in TT in the installer when they're 
available in Inno Setup, but how translators will translate E.G. 
components name? Also languages not supported by Inno Setup (E.G. 
Chinese) can be translated by our translators

**Comment by bear101** [comment]
Hm, yes, ok

**Comment by CoBC** [comment]
Done! So translators can give fr.Client and fr.Full as example to see how to translate components name.

**Comment by Nardol** [comment]
> Also languages not supported by Inno Setup (E.G. Chinese) can be translated by our translators

And will these language actually not supported by Inno Setup be contributed upstream?

**Pull request merged**
