### PR TITLE
Override server dlg type when calling from latest host

### LINKED ISSUE #2351: bug in qt teamtalk. It's not possible to add a laytist host to the server list with the provided option
### Description

When klicking on the add to saved hosts action on the context menu, the view server information dialog appears. But the edit server dialog should appear allowing us to edit the wanted info such as server name and some other info, and then press save and close button to add it to the server list

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

when klicking add to save hosts, the edit server dialog should appear, allowing us to interact with the informations

### Actual behavior

When klicking on add to saved hosts, the view server information dialog appears

### Steps to reproduce problem

press application on a host in the laytist hosts list, and then press enter on add to saved hosts action

### PR DESCRIPTION
**Pull request by CoBC**
Fixes #2351

### CODE REVIEW

**Comment by HanaDadfar** [comment]
I have a better idea
Instead of this, remove the view server dialog mode completely, and let even public servers open the edit server dialog, That's also better than using duplicate server, because for example, lets say I want to save a public server in to my local server list, I press edit server, and then edit the info the way I want, and then press save and close button, It'll add that server to my local server list
also, the duplicate server can only be used if you don't want to edit anything, you only want to add it to the servers list.
Is my idea welcome?

**Comment by HanaDadfar** [comment]
so then the code will also be simple because
server list table with any kind of server and laytist host list with any host will open the update server mode dialog, and the add a new server button will open the create server mode dialog

**Comment by HanaDadfar** [comment]
this way we no longer need to check the server type in void edit server, we only need to check the selection of server so the update server  mode dialog will know what information to fil in the edit boxes.
in anyway I think about this, This is better. Again, You can tell what do you think.

**Comment by HanaDadfar** [comment]
@CoBC do you want to close this pull request and let me implement my provided idea in a new pull request?

**Comment by CoBC** [comment]
> @CoBC do you want to close this pull request
No
> and let me implement my provided idea in a new pull request?
Feel free to open another PR and one of them (mine or your) will be merged, and the other will be closed

**Comment by HanaDadfar** [comment]
ok, so

@CoBC 

and

@bear101 

please, don't merge this pull request so I'll now start to work on my pull request and open it, And you can see

My pull request will completely remove the view server mode from the serverdlg, and it will bring even more benefits than this pull request does, Which will be explaned in the discription of my pull request

Thanks!

**Comment by CoBC** [comment]
Replaced by #2357

**Pull request closed without merging**
