### PR TITLE
Android client: Display empty nicks as anonymous

### PR DESCRIPTION
**Pull request by poretsky**

### CODE REVIEW

**Comment by Oreonan** [comment]
@poretsky can you also labellize edit fields please? Specificly on chat's tab and on MP dialog? I've tried this but I'm very bad on Java :(
@bear101 please think to update translation's files if it's necessary ;)

**Comment by bear101** [comment]
I've changed the blank nickname so it's "NoName - #USERID". Then they will be unique.

**Comment by bear101** [comment]
@Oreonan latest Windows clients can be found here: http://bearware.dk/beta/TeamTalk_v5.6.0.5000_Setup.exe

**Comment by Oreonan** [comment]
@bear101 Yes :) I know :), I wanted to talk about updating the translation for Android if new strings are added. Like "NoName" for example :)

**Comment by Oreonan** [comment]
@bear101 Oh but this string it's already on translation's files, so I've say nothing :), sorry :)

**Comment by bear101** [comment]
@Oreonan I've updated Qt client and Classic client to display "NoName -#USERID" for blank nicknames.

**Comment by Oreonan** [comment]
@bear101 Great :), thanks

**Pull request merged**
