### PR TITLE
Fix tt file import On android 11 and up

### LINKED ISSUE #973: .tt files don't import under android 11 onsamsung galaxy s20
Ever sense updating to the latest teamtalk for android.  I have triedto import a .tt file only to discover when  I went to the server list.  None of the servers I imported were showing up in the server list.  This wasn't a problem in previous versions of teamtalk on Android.

### PR DESCRIPTION
**Pull request by beqabeqa473**
fixes #973

### CODE REVIEW

**Comment by bear101** [comment]
Thanks Beqa. Many will be happy that this is fixed.

**Comment by beqabeqa473** [comment]
it would be great to test on android <= 10 what happens there. I have such device, but cannot test for a while because of work-related things.

**Comment by bear101** [comment]
I've tested on Android 9 with the simulator and the .tt file also works there.

**Comment by beqabeqa473** [comment]
Great, Thanks for helping with test.

On 10/7/23, Bjørn Damstedt Rasmussen ***@***.***> wrote:
> I've tested on Android 9 with the simulator and the .tt file also works
> there.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/2033#issuecomment-1751378900
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Pull request merged**
