### PR TITLE
German translation updates for 5.1.3

### PR DESCRIPTION
**Pull request by schulle4u**

### CODE REVIEW

**Comment by bear101** [comment]
Thanks Steffen!

**Comment by bear101** [comment]
Steffen, can you confirm that the screen reader translates hints for the "master volume", "microphone gain" controls using this version: http://bearware.dk/beta/TeamTalkClassic_v5.1.3.4564_Portable.zip
Replace the German.lng file the one you have just made.

**Comment by schulle4u** [comment]
Confirmed successfully. NVDA as well as narrator recognize all three
slider labels.

**Comment by bear101** [comment]
Good, then I can close #187

**Pull request merged**
