### PR TITLE
Replace language selection by auto detection

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by bear101** [comment]
Shouldn't we make a "show once" dialog that asks the user to choose language?

**Comment by CoBC** [comment]
It's exactly the previous behaviour, but I found it more user friendly 
to set language based on system locale

DO you prefer the previous behaviour with dialog to choose language?

**Comment by bear101** [comment]
Yes, I prefer the previous way. Creating a mapping just adds more maintenance when new languages are added.

**Comment by CoBC** [comment]
OK, closing for now.
However I think to a potential alternative way, we can rename language files to use language codes and so the process will be automatic without any more maintenance needed.
We just have to update settings at first version startup
I still think automatic detection is a more common approach, especially if #2354 is approve, it seams confusing to have an installer in user language and than an app which ask to choose a potential different language

**Pull request closed without merging**
