### PR TITLE
CheckState on models

### PR DESCRIPTION
**Pull request by CoBC**
@bear101 I've let the AccessibleTextRole on Qt5 because CheckState is only accessible in Qt6.

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC it's only on Qt6 you have the notification three times or did you manage to fix it?

Maybe only Qt::CheckStateRole should be used on Qt6 and then remove Qt::AccessibleTextRole?

**Comment by CoBC** [comment]
@bear101 Notification is send three times on all Qt versions with code on issue-1293 branch
I'll make a commit to only use Qt::CheckStateRole on Qt6

**Comment by bear101** [comment]
Shouldn't Qt::AccessibleTextRole also be removed in Qt5 then? To avoid extra notifications.

**Comment by CoBC** [comment]
No, if we remove AccessibleTextRole on Qt5 users can't know if an item is enabled or disabled.

**Pull request merged**
