### PR TITLE
Ability to leave channel from everywhere in main window

### PR DESCRIPTION
**Pull request by CoBC**

### CODE REVIEW

**Comment by peter1384** [comment]
i'm sad that with this pr the join channel action is no longer a togle option and we have a new action leave channel, but ok

**Comment by bear101** [comment]
When you select your own channel then you only have the "Leave Channel" menu item. If you select a user in your channel then you have both "Join Channel" and "Leave Channel". I figure it should show the same in both cases.

**Comment by CoBC** [comment]
Ah yes. What is better, probably to hide "Join channel"?

**Comment by peter1384** [comment]
@CoBC can you just remove JoinChannel and LeaveChannel actions and just make a JLChannel or something else action, and make it toggle between do leave channel and do join channel when it's the case like before?

**Pull request merged**
