### PR TITLE
Option to configure Qt TTS language

### PR DESCRIPTION
**Pull request by CoBC**
@bear101 I tried to refresh available voices when changing language in combobox, but it crashed. Can you try to do this part?

### CODE REVIEW

**Comment by bear101** [comment]
For SETTINGS_TTS_LOCALE and SETTINGS_TTS_VOICE is it ok that I change these settings from int to string. It doesn't look like the index is stable, i.e. the order changes. Also we should sort locales.

Is it ok I make these changes? Changing SETTINGS_TTS_VOICE from int to string will break compatibility

**Comment by CoBC** [comment]
It's ok. Maybe just add a note in change log to inform users that they 
have to reconfigure this settings.

**Comment by bear101** [comment]
@CoBC can you have a look at the changes I've made?

**Comment by CoBC** [comment]
Look good.

**Pull request merged**
