### PR TITLE
Fix vulnerabilities in file transfers

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by amirmahdifard** [comment]
@bear101 please don't limit users maximum files to 100, leave that choise to server admims so they can limit how many a user can send files

**Comment by beqabeqa473** [comment]
it is a performance risk, so for me is ok.

i will have a look at it today.

On 10/4/23, Amir Mahdi ***@***.***> wrote:
> @bear101 please don't limit users maximum files to 100, leave that choise to
> server admims so they can limit how many a user can send files
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/2028#issuecomment-1745961705
> You are receiving this because your review was requested.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by amirmahdifard** [comment]
may be i have a huge server and i wish to allow each user to send up to 500 file for example, but now i have no choise

**Comment by beqabeqa473** [comment]
this was done to guarantee stability.
i won't go in details, but this had its reason.

On 10/4/23, Amir Mahdi ***@***.***> wrote:
> may be i have a huge server and i wish to allow each user to send up to 500
> file for example, but now i have no choise
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/2028#issuecomment-1746197822
> You are receiving this because your review was requested.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Pull request merged**
