### PR TITLE
Publish private server

### PR DESCRIPTION
**Pull request by bear101**

### CODE REVIEW

**Comment by bear101** [comment]
@CoBC The focus issue should work on this branch

**Review by CoBC — COMMENTED** [review]
Focus issue still present. All the rest look good for me.

**Comment by bear101** [comment]
Hm, I cannot see a difference w.r.t. the focus issue. If I connect to a "local" server then the selection and focus is restored. However, if the last server was a public server then the focus is not restored (this was also the behavior in v5.8.3).

**Comment by bear101** [comment]
I take it the focus issue is also present on master-branch, so I'll merge anyway.

**Pull request merged**
