### PR TITLE
Change some sounds

### PR DESCRIPTION
**Pull request by Oreonan**
New sounds for some events. More audible and recognizable
Source: https://lasonotheque.org/search?duree=-1&page=3

### CODE REVIEW

**Comment by bear101** [comment]
Can the user_msg.wav be in higher quality? It's only 8KHz.

**Comment by bear101** [comment]
Is it ok I convert the files to 16-bit, 48000 KHz to save space?

**Comment by Oreonan** [comment]
As long as the quality is the same, no worries for me :)
For the user message sound I will look for a similar sound but of better 
quality

Corentin (certifié Expert NVDA 2019) :

  * Sites Web
      o ProgAccess <https://www.progaccess.net>
      o NVDA-FR <https://www.nvda-fr.org>
  * Réseaux sociaux
      o Twitter : @Oreonan_ <https://www.twitter.com/Oreonan_>
      o Discord : Oreonan#4463
      o Messenger : corentin.bacquecazenave
        <https://m.me/corentin.bacquecazenave>
      o Snapchat : cbc33000 <https://www.snapchat.com/add/cbc33000>
      o Facebook : corentin.bacquecazenave
        <https://www.facebook.com/corentin.bacquecazenave>
      o Instagram : @Oreonan <https://www.instagram.com/Oreonan/>
      o Skype : live:cbc.bacque <Skype:live:cbc.bacque>

Le 28/12/2020 à 21:42, Bjørn Damstedt Rasmussen a écrit :

**Comment by Oreonan** [comment]
@bear101 What do you think about this one: 2a05b1a
Little bit different, but good also :), and better quality

**Pull request merged**
