### PR TITLE
[Review] Request from 'poretsky' @ 'poretsky/TeamTalk5/android-dev'

### PR DESCRIPTION
**Pull request by poretsky**
Please review the following changes:
  * fe09a45 Fixed tools versions to make it work with java 7
  * 4adff64 Added gradle wrapper

As long as gradle directory is mentioned in .gitignore I suspect
that it had been done intentionally for whatever reason,
but gradlew script doesn't work without it in my environment.
Moreover, Android SDK version 25 and Gradle version 2.3.3 require
Java 8 that is now absent on my system and, IMHO, is absolutely
not necessary for the project build at the moment. So, I suggest
these changes to make build process less restrictive. Of course,
if it doesn't break anything.

By the way, I'd like to know whether Android client release is planned
in near future. There was a long-standing bug related to runtime
permissions check and request that I've just fixed. So, I think,
it would be a good time.

### CODE REVIEW

**Comment by beqabeqa473** [comment]
hi.

i agree with first commit about gradle scripts to be integrated in repository.

it makes possible to build project without android studio and some time ago earlier i also added these scripts, but for some reason they  have removed.

**Comment by poretsky** [comment]
Ok. And what are the objections concerning the second one?

Bjoern, what do you think on the matter?

**Comment by beqabeqa473** [comment]
i don't have any problems about second commit also.
it is great that you have fixed also long-standing bug about losing
connection when screen is off.

do you have an idea, why sounds don't work when app is in background?


thanks.

On 10/12/17, Igor B. Poretsky <notifications@github.com> wrote:
> Ok. And what are the objections concerning the second one?
>
> Bjoern, what do you think on the matter?
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/318#issuecomment-335963434


-- 
with best regards beqa

**Comment by bear101** [comment]
Hi Igor. I’m currently on holiday and will look at it when I get back. In the last release I believe I fixed some of the permission issues. But maybe i missed the file IO permission.

**Comment by poretsky** [comment]
Hi Bjoern,

I wish you good time in your holiday. Please, let me know when you are
back. I hope, all fixes and enhancements I've implemented will be tested
carefully up to that moment and, thus, the Android client will be ready
for release.

Beqa, what do you mean talking about sounds in background? As I can see,
everything now works pretty well. Or I do not understand something?

**Comment by beqabeqa473** [comment]
hi.

i mean, when you are minimising teamtalk or locking screen and when
you are pressing button on headset to activate tx, sounds weren't
playing, i don't know how is the situation now after your changes.
unfortunately, i don't have access to my dev machine now and can't
make a build to test.

and one more bug which is anoying is that when you have activated tx,
locked screen when teamtalk is in forground and then unlock the
screen, tx is still on, but people cannot hear you after that.

On 10/15/17, Igor B. Poretsky <notifications@github.com> wrote:
> Hi Bjoern,
>
> I wish you good time in your holiday. Please, let me know when you are
> back. I hope, all fixes and enhancements I've implemented will be tested
> carefully up to that moment and, thus, the Android client will be ready
> for release.
>
> Beqa, what do you mean talking about sounds in background? As I can see,
> everything now works pretty well. Or I do not understand something?
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/318#issuecomment-336695683


-- 
with best regards beqa

**Comment by bear101** [comment]
I can see that it's Android Studio which recommended that I updated to the new gradle version (due to some "instant run" and security enhancements). I don't think I use any of it so it's ok to merge the changes to master branch.

**Comment by beqabeqa473** [comment]
@poretsky @bear101 do you have an idea why sound transmition is interrupting when minimising and then maximising teamtalk again?

**Comment by beqabeqa473** [comment]
@Piciok sorry, i've tested now playing sounds when teamtalk is in background and i can say that this bug has gone.

thank you.

**Comment by OzancanKaratas** [comment]
Hi @poretsky,

Can you push these files? I don't have a broadband Internet access, so cannot fork TeamTalk.
This comment will be deleted after you committing.
[Turkish.zip](https://github.com/BearWare/TeamTalk5/files/1386226/Turkish.zip)

**Comment by poretsky** [comment]
Yes, Beqa, the bug is reproducible, so, I'll try to fix it.

>>>>> "beqa" == beqa gozalishvili <notifications@github.com> writes:

    beqa> @poretsky @bear101 do you have an idea why sound transmition
    beqa> is interrupting when minimising and then maximising teamtalk
    beqa> again?  — You are receiving this because you were mentioned.
    beqa> Reply to this email directly, view it on GitHub, or mute the
    beqa> thread.*

**Comment by poretsky** [comment]
I've fixed it.

>>>>> "beqa" == beqa gozalishvili <notifications@github.com> writes:

    beqa> @poretsky @bear101 do you have an idea why sound transmition
    beqa> is interrupting when minimising and then maximising teamtalk
    beqa> again?  — You are receiving this because you were mentioned.
    beqa> Reply to this email directly, view it on GitHub, or mute the
    beqa> thread.*

**Comment by poretsky** [comment]
Done.

>>>>> "Ozancan" == Ozancan Karataş <notifications@github.com> writes:

    Ozancan> Hi @poretsky, Can you push these files? I don't have a
    Ozancan> broadband Internet access, so cannot fork TeamTalk.  This
    Ozancan> comment will be deleted after you committing.  Turkish.zip

    Ozancan> — You are receiving this because you were mentioned.  Reply
    Ozancan> to this email directly, view it on GitHub, or mute the
    Ozancan> thread.*

**Comment by beqabeqa473** [comment]
ok, thank you.
i will try it out.

On 10/17/17, Igor B. Poretsky <notifications@github.com> wrote:
> Done.
>
>>>>>> "Ozancan" == Ozancan Karataş <notifications@github.com> writes:
>
>     Ozancan> Hi @poretsky, Can you push these files? I don't have a
>     Ozancan> broadband Internet access, so cannot fork TeamTalk.  This
>     Ozancan> comment will be deleted after you committing.  Turkish.zip
>
>     Ozancan> — You are receiving this because you were mentioned.  Reply
>     Ozancan> to this email directly, view it on GitHub, or mute the
>     Ozancan> thread.*
>
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/pull/318#issuecomment-337059191


-- 
with best regards beqa

**Comment by bear101** [comment]
Ok, I've rolled out a new beta

**Comment by poretsky** [comment]
Thanks Bjoern. Just now I've pushed yet a couple fexes more and put this
version under testing. I'll let you know when finish.

**Pull request merged**
