### PR TITLE
Simplify several dialogs

### PR DESCRIPTION
**Pull request by CoBC**
- Only use one dialog to enter username and password on login error and channel share
- Add ability to show password on login error, channel share, channel password and channel operator password

### CODE REVIEW

**Comment by peter1384** [comment]
a strange bug, all dialogs are following each other in auder
When getting the dialog loggin error incorrect username or password, entering the correct information and pressing ok button, brings up the incorrect channel password, pressing ok on that brings up the banned from server dialog.

**Comment by peter1384** [comment]
pressing ok on loggin error dialog brings the incorrect channel password dialog, pressing ok on that brings the not autherised dialog, pressing ok brings banned dialog, and pressing ok repeates this loop from the start again.

**Comment by peter1384** [comment]
also, currently, when we press ctrl+o and we enter the channel operator password incorrectly and press enter, the incorrect operator password dialog is like the banned or not autherised dialog, it has only an ok button. The incorrect channel operator password should be replaced to have a dialog to enter the password again and have the checkbox, like the others, the incorrect channel password dialog for example.

**Comment by peter1384** [comment]
another note for the incorrect channel password dialog
wether you enter the password correctly or incorrectly, It brings the channel not found dialog, And if you enter the password correctly, It won't even join you in to the channel, it just brings the channel not found dialog

**Comment by CoBC** [comment]
Can't reproduce, when I enter the correct password for a channel, I join the channel without any error

**Comment by peter1384** [comment]
@CoBC no, enter the password incorrectly in the first dialog which is channel password dialog, and enter it correctly in the incorrect channel password try again dialog, and see.

**Comment by peter1384** [comment]
Error  dialog  The server reported an error:

Command not authorized

**Comment by peter1384** [comment]
when I do this reproduce with a default account, I get not autherised error, but when i'm doing it with admin account, i'm getting channel not found error
@CoBC Why really? What's the cause?

**Pull request merged**
