### PR TITLE
Option to ignore bot logs in/out

### PR DESCRIPTION
**Pull request by CoBC**
@bear101 Maybe there is a better way to check if an user is a bot or not?

### CODE REVIEW

**Comment by bear101** [comment]
This is more like a hack than a solution. Maybe it should be possible to make a list of usernames to ignore. E.g. in Preferences -> Connection tab.

**Comment by CoBC** [comment]
Hehe yes, it's the goal, but not sure to know how to do it easily :(

**Comment by Muamalaljanahi** [comment]
Or if the client name is not equal to the official client names such as TeamTalk5droid or ITeamTalk, It doesn’t announce login_logout. In this case, not only stats we avoid most of bots like musicBot

**Comment by amirmahdifard** [comment]
i liked @bear101 ' idea: in the client, we should be able to  have a list to import people or bots username to ignor their logged in and outs events, like, i will do this for spammy people.

**Comment by CoBC** [comment]
Closing for now, will be done in another PR later.

**Pull request closed without merging**
