### PR TITLE
Confirmation dialog on server deletion in iOS client

### LINKED ISSUE #1766: Add confirmation before server deletion on iOS
### Description

Currently when deleting a server on iOS client no confirmation is required. Some users seems to remove servers accidentaly, so a confirmation dialog should be add.

### Application

- [ ] qtTeamTalk
- [ ] TeamTalkAndroid
- [X] iTeamTalk
- [ ] TeamTalkServer

### PR DESCRIPTION
**Pull request by CoBC**
Fixes #1766

### CODE REVIEW

**Comment by bear101** [comment]
It does not compile. Also note that UIAlertView was deprecated in iOS 9.0

**Comment by CoBC** [comment]
OK, I made another try. Unfortunately I cannot test myself so I hope this one work better :)

**Comment by bear101** [comment]
It also does not compile... :(

**Comment by CoBC** [comment]
Have you an idea on why? Or maybe can you send the error?

**Comment by bear101** [comment]
/Users/bdr/tt5dist/TeamTalk5_iOS/TeamTalk5/Client/iTeamTalk/iTeamTalk/ServerListViewController.swift:303:13 Cannot find 'confirmationDialog' in scope
/Users/bdr/tt5dist/TeamTalk5_iOS/TeamTalk5/Client/iTeamTalk/iTeamTalk/ServerListViewController.swift:305:15 Cannot find 'Button' in scope
/Users/bdr/tt5dist/TeamTalk5_iOS/TeamTalk5/Client/iTeamTalk/iTeamTalk/ServerListViewController.swift:311:15 Cannot find 'Text' in scope

**Comment by bear101** [comment]
It still does not compile. Please only make pull requests that has been tested prior to submission.

**Comment by CoBC** [comment]
Unable to test for now. I'm trying to find a way to build iOS client :)
So, maybe try again later.

**Pull request closed without merging**
