### PR TITLE
Format dates and times to user locale

### PR DESCRIPTION
**Pull request by CoBC**
Affect banned users dialog, files model and user accounts dialog

### CODE REVIEW

**Comment by CoBC** [comment]
Hmm, strange, it works as expected here. Do you also reproduce the 
freeze on user accounts dialog?

**Comment by bear101** [comment]
I ran in Visual Studio Debug mode when I tested. On my mac it runs slow but ok.

Also notice that sorting does not work with the change. Danish locale date is DD/MM/YYYY but then 31 of any month is last.

**Comment by CoBC** [comment]
I guess we can merge it like this for now. We have to rework sorting on banned users dialog. I'll try to work on it more later.

**Comment by CoBC** [comment]
@bear101 Note, sorting by size is also broken, E.G. 995Mo is shown after 1.0Go and not before.
So, we probably have to rework on sort filters for size and for this PR with date format.
Do you have any idea on how to fix it, maybe we should return diferent values for display role and user role and force sort to be done on one role, but not sure.

**Comment by CoBC** [comment]
@bear101 It works as expected for me now with date.

**Pull request merged**
